### ISSUE TITLE
Support the Actor table

### ISSUE THREAD

**Issue by jayktaylor** [ciencia/mediawiki-extensions-StubUserWikiAuth#2]
As you're aware, MediaWiki 1.31 and higher use the [actor table](https://www.mediawiki.org/wiki/Manual:Actor_table) for storing information about users who make revisions, perform log actions, etc.

I'm still using this on a wiki which is on 1.30, which is all good for now, but eventually it may be good for us to upgrade and this extension is probably a key thing that would be blocking for us. No rush, but definitely worth thinking about building support for 👍

**Comment by ciencia** [comment]
Fortunately, MediaWiki 1.31 and the upcoming 1.32 are not using the actor table yet, because [$wgActorTableSchemaMigrationStage](https://www.mediawiki.org/wiki/Manual:$wgActorTableSchemaMigrationStage) defaults to a value that ignores the new schema. This would be a priority for 1.33, though

**Comment by jayktaylor** [comment]
For sure - sorry, the original issue text makes it sound like you can't use 1.31 without using the actor table which is obviously incorrect.

**Comment by ciencia** [comment]
Fixed in b9ce24ccc6e9830d59d066a5d93e2106285bd1f2

This only needed a change to the maintenance script, which is only run once when the extension is first installed
